---

- name: Check if postgresql service exists
  stat: path=/etc/init.d/postgresql
  register: service_status

- name: stop postgresql service because we want to expose 5432 via docker
  service: name=postgresql state=stopped
  when: service_status.stat.exists
  register: service_stopped
  become: yes

- name: pull postgres docker image
  docker_image:
    name: "{{ image_repository_url }}"
  become: yes

- name: run the postgres docker container
  docker_container:
    name: "{{ postgres_container_name }}"
    image: "{{ image_repository_url }}"
    ports:
      - "5432:5432"
  become: yes